FROM ubuntu:latest
RUN apt update
RUN apt install gcc-arm-linux-gnueabi -y
RUN apt install gcc-aarch64-linux-gnu -y 
RUN apt install binutils-gold -y
RUN apt install nano -y
RUN useradd user --home /home/user
COPY ld-linux-aarch64.so.1 /lib/
USER user
WORKDIR /home/user